apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
  namespace: test-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapp
      labels:
        app:mavenwebapp
    spec:
      containers:
      - name: mavenwebapp
        image: sudheeradoc/maven-web-application:TAG
        ports:
        - containerPort: 8080
   

  
